# Generated by Django 5.2.5 on 2026-01-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_fcmtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bank_account_name',
            field=models.CharField(blank=True, help_text='Account holder name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, help_text='Bank account number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bank_code',
            field=models.CharField(blank=True, help_text='Flutterwave bank code', max_length=10, null=True),
        ),
    ]
