# Generated by Django 6.0.1 on 2026-01-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrandLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.TextField(blank=True)),
                ('mode', models.CharField(choices=[('DEVICE', 'Device'), ('STATIC', 'Static')], max_length=10)),
            ],
        ),
    ]
