# Generated by Django 5.2.5 on 2026-01-10 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('errands', '0004_errand_expires_at_errand_is_open_errand_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrandLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('GO_TO', 'Go To'), ('RETURN_TO', 'Return To')], max_length=10)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.TextField()),
                ('errand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='errands.errand')),
            ],
        ),
    ]
