# Generated by Django 6.0.1 on 2026-01-23 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('errand_location', '0001_initial'),
        ('errands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='errandlocation',
            name='errand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='errands.errand'),
        ),
    ]
