# Generated by Django 5.2.5 on 2026-01-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errand_location', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='errandlocation',
            name='errand',
        ),
        migrations.RemoveField(
            model_name='errandlocation',
            name='kind',
        ),
        migrations.AddField(
            model_name='errandlocation',
            name='mode',
            field=models.CharField(choices=[('DEVICE', 'Device'), ('STATIC', 'Static')], default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='errandlocation',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
