# Generated by Django 5.2.5 on 2026-01-13 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errand_location', '0002_remove_errandlocation_errand_and_more'),
        ('errands', '0006_alter_errand_go_to_alter_errand_return_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='errandlocation',
            name='errand',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='errands.errand'),
            preserve_default=False,
        ),
    ]
