# Generated by Django 6.0.1 on 2026-01-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_userlocation_delete_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocation',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
