# Generated by Django 5.2.5 on 2026-01-12 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('errands', '0005_errand_price_errand_runner_alter_errand_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Escrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount held in escrow', max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RELEASED', 'Released'), ('REFUNDED', 'Refunded'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_id', models.CharField(blank=True, help_text='External payment transaction ID', max_length=255, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escrows_as_buyer', to=settings.AUTH_USER_MODEL)),
                ('errand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escrow', to='errands.errand')),
                ('runner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escrows_as_runner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['buyer', 'status'], name='escrow_escr_buyer_i_c90523_idx'), models.Index(fields=['runner', 'status'], name='escrow_escr_runner__c12009_idx'), models.Index(fields=['errand'], name='escrow_escr_errand__d1c5a1_idx')],
            },
        ),
    ]
