# Generated by Django 5.2.5 on 2026-01-09 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errands', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='errand',
            old_name='description',
            new_name='instructions',
        ),
        migrations.RemoveField(
            model_name='errand',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='errand',
            name='dropoff_latitude',
        ),
        migrations.RemoveField(
            model_name='errand',
            name='dropoff_longitude',
        ),
        migrations.RemoveField(
            model_name='errand',
            name='pickup_latitude',
        ),
        migrations.RemoveField(
            model_name='errand',
            name='pickup_longitude',
        ),
        migrations.RemoveField(
            model_name='errand',
            name='requester',
        ),
        migrations.RemoveField(
            model_name='errand',
            name='title',
        ),
        migrations.AddField(
            model_name='errand',
            name='payment_method',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='errand',
            name='speed',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='errand',
            name='type',
            field=models.CharField(choices=[('ONE_WAY', 'One Way'), ('ROUND_TRIP', 'Round Trip')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='errand',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='errand',
            name='status',
            field=models.CharField(default='DRAFT', max_length=20),
        ),
    ]
