# Generated by Django 5.2.5 on 2026-01-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errands', '0002_rename_description_errand_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='errand',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
