# Generated by Django 5.2.5 on 2026-01-13 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errands', '0004_errand_expires_at_errand_is_open_errand_updated_at_and_more'),
        ('locations', '0002_userlocation_delete_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='errand',
            name='go_to',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='errands_go_to', to='locations.userlocation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='errand',
            name='return_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='errands_return_to', to='locations.userlocation'),
        ),
    ]
