# Generated by Django 5.2.5 on 2026-01-12 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errands', '0004_errand_expires_at_errand_is_open_errand_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='errand',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price for the errand (required for escrow)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='errand',
            name='runner',
            field=models.ForeignKey(blank=True, help_text='Runner who accepted the errand', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_errands', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='errand',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errands', to=settings.AUTH_USER_MODEL),
        ),
    ]
