# Generated by Django 5.2.5 on 2026-01-13 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errand_location', '0002_remove_errandlocation_errand_and_more'),
        ('errands', '0005_errand_go_to_errand_return_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errand',
            name='go_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errands_go_to', to='errand_location.errandlocation'),
        ),
        migrations.AlterField(
            model_name='errand',
            name='return_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='errands_return_to', to='errand_location.errandlocation'),
        ),
    ]
