# Generated by Django 5.2.5 on 2026-01-13 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errand_location', '0003_errandlocation_errand'),
        ('errands', '0006_alter_errand_go_to_alter_errand_return_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errand',
            name='go_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='errands_go_to', to='errand_location.errandlocation'),
        ),
    ]
