# Generated by Django 5.2.5 on 2026-01-15 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errands', '0007_alter_errand_go_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='errand',
            name='instructions',
        ),
        migrations.CreateModel(
            name='ErrandTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField(help_text='Price in XAF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('errand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='errands.errand')),
            ],
        ),
    ]
