# Generated by Django 5.2.5 on 2026-01-17 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errands', '0008_remove_errand_instructions_errandtask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='errand',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='errand',
            name='quoted_distance_fee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='errand',
            name='quoted_service_fee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='errand',
            name='quoted_total_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='errand',
            name='runner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_errands', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='errand',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('ONLINE', 'Online')], max_length=20),
        ),
        migrations.CreateModel(
            name='ErrandOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(help_text='Order of offer')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10)),
                ('expires_at', models.DateTimeField()),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('errand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='errands.errand')),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('errand', 'runner')},
            },
        ),
    ]
